nvpps: Add missing header of.h
Building the NVPPS driver with Linux v6.9-rc1 is failing with the
following error ...

 drivers/nvpps/ptp-notifier.c:125:69:
 error: invalid use of undefined type 'const struct device_node'

Add the header file of.h to fix this build issue.

Bug 3826818
Bug 4471899

Change-Id: I0eb23e3556ec280447e3d2c499afc11daad601a0
Signed-off-by: Jon Hunter <jonathanh@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nv-oot/+/3104379
GVS: Gerrit_Virtual_Submit <buildbot_gerritrpt@nvidia.com>
Reviewed-by: Paritosh Dixit <paritoshd@nvidia.com>
Reviewed-by: svcacv <svcacv@nvidia.com>