ASoC: tegra: Fix redefinition error for Linux v6.11
In Linux v6.11, commit 1a251f52cfdc ("minmax: make generic MIN() and
MAX() macros available everywhere") causes the Tegra ASoC Utils driver
build to fail with the following error:

 sound/soc/tegra/tegra_asoc_utils.c:18: error: "MAX" redefined [-Werror]
  18 | #define MAX(X, Y) ((X > Y) ? (X) : (Y))

Fix this by add guards around the definition of 'MAX' in the
Tegra ASoC Utils file.

Bug 4749580

Change-Id: I63df434627e6ee7ab16d865c296b07b91405fdfd
Signed-off-by: Jon Hunter <jonathanh@nvidia.com>
Reviewed-on: https://git-master.nvidia.com/r/c/linux-nv-oot/+/3185143
Reviewed-by: Sameer Pujar <spujar@nvidia.com>
GVS: buildbot_gerritrpt <buildbot_gerritrpt@nvidia.com>